import { useEffect, useState, useRef } from 'react';
import Head from 'next/head';
import { useInView } from 'react-intersection-observer';
import { useAnimation } from 'framer-motion';
import About from '../components/About';
import Contact from '../components/Contact';
import Projects from '../components/Projects';
import Header from '../components/Header';
import Navbar from '../components/Navbar';
import Technologies from '../components/Technologies';
import FloatingButtons from '../components/FloatingButtons';

export default function Home() {
  const [navScroll, setNavScroll] = useState(false);
  const [active, setActive] = useState(false);
  const [isMounted, setIsMounted] = useState(false);
  const controls = useAnimation();
  const { ref, inView } = useInView({
    threshold: 0.5,
  });
  const scrollRef = useRef(null);

  // useEffect(() => {
  //   scrollRef.current;
  // }, []);

  useEffect(() => {
    const handleScroll = () => {
      window.scrollY >= 70 ? setNavScroll(true) : setNavScroll(false);
    };

    window.addEventListener('scroll', handleScroll);
  }, []);

  useEffect(() => {
    if (inView) {
      controls.start('visible');
    }
  }, [controls, inView]);

  useEffect(() => {
    setIsMounted(true);
  }, []);

  useEffect(() => {
    active
      ? (document.body.style.overflow = 'hidden')
      : (document.body.style.overflow = 'unset');

    const handleScroll = () => {
      if (window.innerWidth > 768) {
        setActive(false);
      }
    };

    window.addEventListener('resize', handleScroll);
  }, [active]);

  return (
    <div className='dark:bg-gray-900 dark:text-white relative transition-all duration-1000 bg-gray-100 scroll-smooth'>
      <Head>
        <title>Rosanno Personal Website</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar navScroll={navScroll} active={active} setActive={setActive} />
      <Header ref={scrollRef} />
      <About ref={ref} controls={controls} />
      <Technologies />
      <Projects />
      <Contact />
      <FloatingButtons isMounted={isMounted} />
    </div>
  );
}
